running...
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
not sorted
['./data/imagenet/train/n02814533', './data/imagenet/train/n02113799']
(32, 32, 3)
(32, 32, 3)
(32, 32, 3)
(32, 32, 3)
(32, 32, 3)
(32, 32, 3)
(32, 32, 3)
(32, 32, 3)
(8, 3, 32, 32)
(8,)
anderes: 
not sorted
['./data/imagenet/val/n02814533', './data/imagenet/val/n02113799']
(32, 32, 3)
(32, 32, 3)
(32, 32, 3)
(32, 32)
(32, 32, 3)
(32, 32, 3)
(32, 32, 3)
(32, 32, 3)
Traceback (most recent call last):
  File "codebase/main.py", line 7, in <module>
    from dataloadersCollection import dataloaders
  File "/home/user/experiments/codebase/dataloadersCollection.py", line 3, in <module>
    from imagenetData import IMAGENET_dataloaders
  File "/home/user/experiments/codebase/imagenetData.py", line 128, in <module>
    testImagenetDataLVL1 = ImagenetLvL1(train= False, transform=transform)
  File "/home/user/experiments/codebase/imagenetData.py", line 94, in __init__
    imgData = imgData.reshape(lenght,3, imageSize ,imageSize) # brauche ich das ?
ValueError: cannot reshape array of size 22528 into shape (7,3,32,32)
